
version: 2.1

jobs:
  
  integration-dbt-utils-sqlserver:
    docker:
      - image: dataders/pyodbc:1.2
    steps:
      # only needed until I add Git to the Docker container
      - run:
          name: "TEMP: install Git"
          command: |
            apt-get install -y git

      - checkout

      - run: &pull-submodules
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: "TEMP: install dbt-utils"
          command: |
            git clone --recursive https://github.com/fishtown-analytics/dbt-utils 
      
      - run: &setup-dbt
          name: "install python deps"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools
            pip install dbt-sqlserver

      - run:
          name: "move files"
          command: |
            echo 'current folder'
            pwd
            echo 'recursive list of all files and dirs'
            ls -R -A --ignore='venv' --ignore='git'
            cp integration_tests/ci/sample.profiles.yml profiles.yml
            echo 'is profiles.yml here?'
            ls
      
      - run:
          name: "test profile exists in correct spot"
          command: |
            pwd
            FILE=profiles.yml
            if test -f "$FILE"; then
                echo "$FILE exists."
            fi

      - run:
          name: "Run Tests - dbt-utils"
          command: |
            . venv/bin/activate
            cd /root/project/integration_tests/dbt_utils
            dbt deps --target sqlserver
            dbt seed --target sqlserver --full-refresh
            dbt run --target sqlserver --full-refresh
            dbt test --target sqlserver
      
      - store_artifacts:
          path: ./logs


workflows:
  version: 2
  test-all:
    jobs:
      - integration-dbt-utils-sqlserver
